### ISSUE TITLE
[Adjustable Damage Number Size]Some Errors in the reframework log

### ISSUE THREAD

**Issue by Reny900** [GreenComfyTea/MHR-Better-Matchmaking#1]
The mod looks functional nonetheless, but since it prints them as errors it might be worth the report, i think?
Anyway, here's [wonderwall](https://github.com/GreenComfyTea/MHR-Better-Matchmaking/files/15367458/re2_framework_log.txt)

**Comment by GreenComfyTea** [comment]
Your only errors are corrupted config files for Adjustable Damage Number Size, Better Matchmaking and Buffer Bindings. Just delete the files.
